version: "3.8"
name: microcommunication

services:
  api:
    build:
      context: ../../src/api
      dockerfile: Dockerfile
    ports:
      - "5100:8080"
    environment:
      - Database=CosmosDB
      - RandomApiUrl=http://random:8090
      - Cors=http://localhost:8080
    env_file:
      - .env
    depends_on:
      - random

  random:
    build:
      context: ../../src/random
      dockerfile: Dockerfile
    env_file:
      - .env

  web:
    build:
      context: ../../src/web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:5100
    depends_on:
      - api
