version: "3.8"
name: microcommunication

services:
  api:
    build:
      context: ../../src/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - Database=CosmosDB
      - RandomApiUrl=http://random:8090
    env_file:
      - .env
    depends_on:
      - random

  random:
    build:
      context: ../../src/random
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - .env

  web:
    build:
      context: ../../src/web
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - API_URL=http://localhost:8080
    depends_on:
      - api

  # cosmosdb:
  #   image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
  #   hostname: cosmosdb
  #   mem_limit: 3g
  #   cpus: 2.0
  #   ports:
  #     - "8081:8081"
  #     - "10251:10251"
  #     - "10252:10252"
  #     - "10254:10254"
  #   environment:
  #     - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
  #     - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
