name: Build and push Docker images
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v1

      - name: Build API image
        run: docker build src/api/ --file src/api/Dockerfile --tag robinmanuelthiel/microcommunication-api:${{ github.run_id }}.${{ github.run_attempt }} --tag robinmanuelthiel/microcommunication-api:latest

      - name: Build Random image
        run: docker build src/random/ --file src/random/Dockerfile --tag robinmanuelthiel/microcommunication-random:${{ github.run_id }}.${{ github.run_attempt }} --tag robinmanuelthiel/microcommunication-random:latest

      - name: Build Web image
        run: docker build src/web/ --file src/web/Dockerfile --tag robinmanuelthiel/microcommunication-web:${{ github.run_id }}.${{ github.run_attempt }} --tag robinmanuelthiel/microcommunication-web:latest

      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push API image
        run: docker push robinmanuelthiel/microcommunication-api

      - name: Push Random image
        run: docker push robinmanuelthiel/microcommunication-random

      - name: Push Web image
        run: docker push robinmanuelthiel/microcommunication-web
